local random = require 'common.random'
local factory = require 'factories.text_random_spawn_factory'

-- Requirements for entityLayer while makeMap
-- (Handled by entityLayer:gsub("[GAP ]", "P", 1):gsub("[GAP ]", "A"))
-- 1. Atleast one "P"
-- 2. All probable locations should be have A
--
-- Requirements for entityLayer while using it to generate randomGoals
-- 1. Place G where you want the possible goal locations to be
-- 2. The robot will spawn at some random location at distance > 8 from chosen G
-- 3. Apples will be replace with Apple at scatteredRewardDensity probability
local entityLayer_01 = [[
*****************************************************************************************************
*PAA*AAAAAAAAA*AAAAAAAAAAAAAAAAAAA*A*AAAAA*AAA*AAAAAAAAAAAAAAA*AAAAAAA*AAAAAAA*AAAAAAAAAAAAAAA*AAAAA*
*AAAAAA*AA*A*A*****A*****A***AA**A*AAAAA*A*A*A*A******A******A*A*A**A**A*A***A***A***AA**A*A*A**AAAA*
*A*AAAAAAA*A*A*AAA*AAAAA*A*AAA*AAA*A*A*A*A*A*A*AAA*A*AAAAAAAAA*A*A*AAAAA*AAA*AAA*AAA*AAA*A*A*AAAAA*A*
*AA***AA***A*A*A*A***A*A***A***A*A*A*A*AA*AA*AA**AAA*A*********A*A*A***A***AA**A*A****AA*A*A***A***A*
*A*AAAAA*AAA*AAA*AAAAA*A*AAA*AAA*AAAAA*AAA*A*AAAAAAAAA*AAAAAAAAA*AAAAAAAAA*A*A*AAAAAAA*AAA*A*AAAAAAA*
*A*A**A**A**********AA*A*AA**A***A**A**AAAAA**A**A*AAA*A***********A*****A*A*A*******A***A*A*******A*
*A*A*AAA*AAAAAAAAA*AAAAAAAAA*A*A*A*AAAAA*AAA*AAA*AAAAA*A*AAAAAAAAAAAAAAA*A*A*AAA*AAA*AAAAAAAAA*AAA*A*
*A*A***A***A*****AA********A*A*AAA***A*******AAA***AAA*A*A**********A**A***A***A*A*A***A**A**A*AAA*A*
*A*AAA*AAAAAAAAA*AAAAA*AAAAA*A*A*AAA*AAAAAAA*A*AAAAA*AAA*AAA*AAAAAAAAA*AAA*AAA*AAA*AAAAAAAAA*AAAAA*A*
*A***A*A*A*A*A*******A*A*A***AAAA*AA***A*AA*AA**AA***A*A**AA*A***A***AA**A*AAA***A***A*****A*****A*A*
*AAA*A*AAA*AAA*AAA*AAA*A*AAAAA*AAA*AAA*A*A*AAA*AAAAAAA*AAA*AAAAAAA*AAA*A*AAA*AAA*AAA*AAAAA*AAAAAAA*A*
*A*AAA***AAAAA*AAA*A***A*A*A**A**A**AA*A*A*A*********A*A**A***A****A*A*A*A*A***A***A*A***A*A*******A*
*A*A*AAA*A*A*A*A*AAA*AAA*AAA*AAAAAAA*AAA*A*AAAAA*AAAAA*A*AAAAAAAAA*A*AAA*AAAAAAA*AAAAA*AAA*AAAAAAA*A*
*A*A***A***A**AA***A*****A***A*A****AA******AA*A*AAA*A*A*AA*A****A*AAA*A*******A*A*****A*A***A*A***A*
*A*AAA*AAA*AAA*AAAAA*AAA*A*AAA*AAAAAAA*AAAAAAAAA*AAA*A*A*AAAAA*A*AAA*A*A*AAAAAAAAAAAAAAA*AAAAA*AAAAA*
*A*A*AA**A***AA*AA***A*A*A*A*A***A****AA****A******A*A***A***A*A*****A*A*AA*******AA**A********A*A*A*
*AAA*A*AAA*AAAAAAAAAAA*A*AAAAAAA*A*AAAAAAAAAAA*AAAAA*AAAAAAAAA*AAA*AAA*AAAAAAAAAAA*A*AAAAAAAAAAA*A*A*
*A*****A***A***A*A*A*A*A*******A**AA*AAA*****A*A*A*A****A**AAA*AAA*A****A**A**AA*AAA*************A*A*
*AAAAA*A*AAA*AAAAA*AAA*AAAAAAA*AAAAAAAAAAAAAAAAAAA*AAAAAAA*AAAAA*AAA*AAAAAAA*AAA*A*AAAAA*AAA*AAAAA*A*
*A***AAAAA***************A***A*A***A**A**A*A****AAA***A**A**AA*A**A**A***A*A***AAA*****A*A*A*AA****A*
*AAA*AAA*AAAAAAA*AAAAAAA*AAA*AAAAA*A*AAA*A*AAAAA*A*AAAAAAAAAAAAA*AAAAA*AAA*AAAAA*AAAAA*AAA*A*AAA*AAA*
***A*****A*A***A*AA**A*A*******A*A***A*A***AAAAA*A**A**A****A**A*A*****A*AA*A****A***A***A*A***AAA***
*AAA*AAA*A*AAAAA*A*AAA*AAAAAAAAA*AAAAA*AAAAAAA*A*A*AAA*AAA*AAAAA*AAA*AAA*AAAAAAAAAAAAA*AAA*AAA*A*AAA*
*A***A*A*A*A*A***A*A*A*A*A*AA**A***A*A******AA*A*A*A*A*****AA******A*A*******A***A*A*A*A*A*AAA*AA**A*
*AAAAA*AAA*A*A*AAAAA*AAAAAAAAAAAAAAAAA*AAAAAAA*A*AAA*AAAAAAA*AAAAA*A*AAAAAAAAA*AAA*AAAAA*A*AAA*A*AAA*
*A*****A*A*A***AA*AA*****A**A******A*A*A***A***A*A****A****A*AAA*A*A***A*****AAAA*AA***A***A***A*A***
*A*AAAAAAA*AAA*A*AAAAAAA*A*AAAAAAAAA*AAA*AAA*AAAAA*AAA*AAAAAAA*A*A*AAAAAAA*A*A*AAAAAAA*AAA*AAA*A*AAA*
*A*A****A****A*A*A***A*A*A*AAAA**A*******AAA*A***A*A*AAA******AA*A*A*****AAA*A*******A***A***A*A***A*
*A*AAA*AAAAAAA*A*AAAAA*A*A*AAAAA*AAAAAAAAAAA*A*AAA*A*A*A*AAAAAAAAAAA*AAAAAAA*AAAAA*A*AAA*AAA*AAA*AAA*
*A***AA**A***A*A*****A*A*A*****AA************A*A**AA*A*A*A***A*A*A***A*A*A**A**A*A*A*A*AAA*******AAA*
*A*AAA*AAA*A*AAA*AAAAA*A*AAAAA*A*A*AAAAAAAAAAA*A*AAA*AAA*A*AAA*A*AAA*A*AAAAAAA*A*A*AAA*AAAAAAAAAAA*A*
*A*A***A***A*A*AAA*A*A*A***A***A*A*A*A***A*A***A*A*A*****A*A*A*AA**A*A*A**A**A*AAA*A***A*A*A***A***A*
*AAAAAAA*AAA*A*A*AAA*A*A*AAA*AAA*AAA*A*AAA*AAA*AAAAA*AAAAA*AAA*AAA*AAA*AAA*AAA*AAA*AAAAA*A*A*AAA*AAA*
*********A***A*A*A*A*A*A*A*A*A***AA**A*A*****A*******A*******A***A***A*AAA*AA*AA**AA*A*A*AAA*A***A***
*AAAAAAA*AAAAA*AAA*AAA*AAA*A*A*A*AAA*A*AAAAAAAAA*AAA*AAAAAAAAA*AAAAA*AAA*AAAAA*AAA*AAAAAAA*A*AAA*AAA*
*AA****A*A***AAAAA*A*******AAAAAA**A*A**A**A***A*A*A*AAA*******A****AA***A*A*A***A*AAA*****A***A*A*A*
*A*AAAAA*A*AAAAAAA*AAA*AAAAA*A*A*AAAAA*AAA*A*A*A*A*AAA*AAAAA*AAA*AAAAA*AAAAA*AAA*A*A*A*AAA*AAA*A*A*A*
*A***A****AA*****A**AA*A*A*A*A*A*A*A*AA**A*A*A*A**AA*A*A*A*A*A***A****AA*****A*A*A*A*A*A*A**AA*A*A*A*
*AAA*AAAAA*AAA*A*AAAAA*A*A*A*A*A*AAA*AAA*AAAAA*AAA*AAA*A*A*AAA*AAA*AAA*AAAAAAAAAAAAA*AAA*A*AAA*A*AAA*
***A*****A*AAA*A*A**A*A**A***A*A***A*A*A*AAA****AA*A***AAAA**A*A***A*A*************A*A**AA*A***A*****
*AAA*AAAAA*A*A*AAAAAAAAA*A*AAA*AAA*A*AAA*AAAAAAAAA*AAA*AAAAAAAAAAA*AAAAA*AAAAAAA*A*A*AAA*AAA*AAA*AAA*
*A*A*A*******A*A*******A*A*A***A***A*AA**A***A******AAAA*A*****A*A*A***A*A*****A*A*AAA*AA**A*A***A*A*
*AAA*AAAAAAAAA*AAAAA*AAA*A*AAAAAAAAA*AAA*AAA*AAAAAAAAAAAAAAAAA*AAA*A*A*AAA*A*AAA*A*AAA*AAAAA*AAAAA*A*
**AA*AA********A*A**AA***A**AA***A*****A*A*A*****A*A***AA**A*A***A*A*AA****A*A*A*A*****A***AA*****AA*
*A*AAAAAAAAAAAAA*AAA*AAA*AAA*AAA*AAA*AAAAA*A*AAAAAAA*AAA*AAA*AAAAA*A*AAAAAAA*AAA*AAA*AAAAA*AAAAAAA*A*
*AA*A*****AAAA*A*AAA***A*A*****A*A***A*A*A*A*AA*********AA*******AAA*A*****A***A*AAAA*AA*AA**A*A*A*A*
*AAA*AAAAA*A*A*AAA*A*AAAAA*AAAAA*A*AAA*AAA*AAAAAAAAAAAAAAA*AAAAAAA*A*AAAAA*AAA*A*A*AAAAA*AAA*AAA*AAA*
*A***A*A*A*A*A*A**AAAA***A*A*****A*A***A***A*A***A*A*A***AAA*****A*A**A**AA*AAAA*A*A**A**A***A*****A*
*AAAAA*A*AAA*A*AAA*AAA*AAAAA*AAA*A*A*AAA*AAA*A*AAAAA*A*AAAAAAA*AAA*AAAAAAA*AAA*A*A*A*AAA*A*AAAAA*AAA*
*A***A*A*****A*****A*A*A*****A*A*A*A*A***A***A*A***AAA*******A*************A*A*AAA***A*A***A***A*AA**
*A*AAA*AAAAA*AAAAA*AAA*AAA*AAA*A*A*A*AAA*A*AAAAA*AAA*AAAAAAAAA*AAA*AAAAAAA*A*AAA*AAAAA*AAA*AAA*AAA*A*
*A*A*A*A*A*A*A***A*A*A***AAA*A*A***AA*AAAA*A*****A**AA**A****A*A*A*AA*AA***A*A***A*A*A***A*A***A*A*A*
*A*A*A*AAA*AAAAAAAAAAAAAAAAAAA*AAA*A*AAA*A*AAAAAAAAAAAAA*AAAAA*A*AAAAAAAAAAA*AAA*A*A*A*A*AAA*AAA*AAA*
*A*A*A*****AAA**A*******A**A*A*A*AAA*A*AAA*****AA****A***A****AA*A***AAA**A****A*AAA*A*A*****AAAA**A*
*AAAAA*A*AAA*AAAAAAA*AAAAAAAAA*A*AAA*AAA*AAAAA*A*AAAAA*AAAAAAA*A*AAA*AAA*AAA*AAAAA*A*AAA*AAA*A*A*AAA*
*****A*A*A***A*A***A*A***A*AAAAA*A*A*A*A*****A**AA***A*A******AA*AAA***A*AA**A**A**A***A*A*A*A*A*A***
*AAA*A*AAA*AAA*AAA*AAA*AAAAAAA*AAAAAAA*A*AAA*A*AAA*AAA*A*AAAAAAA*A*AAAAA*AAA*AAAAA*AAA*A*A*A*A*A*AAA*
***A*AAA*A*A**AA*A**A******A*A***A*A*A*A*A*A*A*A*******A*A*******A*******A*A***AAA*AA*AA*A*A*A*****A*
*AAA*AAA*AAA*AAA*AAAAAAAAA*A*AAA*A*AAA*A*A*A*A*AAA*AAAAA*AAAAAAAAAAAAA*AAA*A*AAAAA*A*AAA*AAAAAAAAA*A*
*A*****AAA*A*A*********A*A*A**AA*A***A*A***AAA***A*A*****A*****A*A*A*A***A*A*A*****AAAA****A****AA*A*
*AAAAA*A*A*A*A*AAAAAAAAAAA*AAA*A*AAA*A*AAA*A*AAA*AAA*AAAAAAAAAAA*A*A*AAA*A*A*A*AAAAAAA*AAAAAAA*A*A*A*
*A***A*AAA*A*A*A***A**A****A*A*A*A*A*AA**A*AA**AAA**AA*A**A****A*A*A**AAAA*A*A*A*AAAAA*A**AA*A*A*A*A*
*AAA*AAA*AAA*AAAAAAAAAAAAAAA*A*AAA*A*AAAAA*A*AAA*AAAAA*A*AAAAA*A*A*A*A*A*AAA*A*A*AAA*A*AAA*A*A*A*A*A*
**AA****A****AA**A****A*AAA*****AA*A*A*A***A*AA***A**A*A*A*****A*A*AAA*A*A***A***A*A*A*A*A*A*A*A*A*A*
*A*AAAAAAA*AAAAAAA*AAA*AAA*AAAAAAA*A*A*AAAAAAA*AAAAA*A*A*AAAAAAAAAAA*AAAAAAAAA*AAA*A*A*A*A*AAA*A*A*A*
*A*******A*AA******AA**A***AA**A***A*A*AAA***A*AA*AA*A*A*****A***A*A***A**AA***A***A*A***A*AA**A*A*A*
*AAAAA*AAAAAAA*A*AAAAAAA*AAAAAAAAAAAAA*A*A*AAA*AAAAAAAAA*AAA*AAA*A*GAAAA*AAA*AAA*A*AAAAA*AAAAA*AAAAA*
*A*****AA**A*AAA*A*A*****A***A**A**A*A*A*A*A***AA******A*A*A***AAA*****A*A*****A*A*A***A*A***A*A***A*
*A*AAAAA*AAA*A*AAAAAAAAA*AAAAA*AAAAA*AAAAA*AAA*AAAAAAAAAAA*AAAAA*AAAAA*AAA*AAAAA*AAA*A*AAAAAAAAAAAAA*
*A*A*****A***A*A***A*A*AAA*****A*A***A*******A***A********A**A*A****AA*****A*****A***A*A***AA*A****A*
*A*AAAAA*AAAAAAAAA*AAA*AAA*AAA*A*AAAAAAAAAAA*AAA*A*AAAAAAAAA*AAAAA*AAA*AAAAAAA*A*AAA*A*AAA*AAAAAAA*A*
*A***A*A*A*A***A*A***A*A***A*AAA******A****A***AAA*A***AAA*A*A*A*A*A*A*A***A*A*AA**A*A***A***A***A*A*
*AAA*AAA*A*AAAAA*A*AAA*AAAAA*A*AAA*AAAAAAA*AAAAAAA*AAA*AAA*AAA*A*AAA*AAAAA*AAA*AAA*A*AAA*AAA*AAA*A*A*
*AAA*A***A*******A*A*A*A**A**A**AA*A***A**AA***A*****A*A*A****AA***********A***A*A*AA**A***A***AAA*A*
*A*A*AAA*AAA*AAA*A*A*AAA*AAA*AAA*AAA*AAA*AAA*AAAAA*AAA*AAA*AAAAA*AAA*AAAAA*AAA*A*AAAAAAAAAAA*A*A*A*A*
*A*A***A***A*A*A*A*A*A*A***A*A*A*A***A***A***AA**A*A*******A*****A*AAAA**A***AA*A*A********A*A*A*AAA*
*A*AAAAAAA*A*A*A*AAA*AAAAAAA*A*A*AAA*AAA*AAAAA*AAAAAAAAAAAAA*AAAAA*A*A*AAAAA*A*AAAAA*AAAAAAA*A*AAAAA*
*A*A*AA**A*A*A*******A*A*A*A*A**A**A*A*AA******A******A******A*****A*AAA**AA*A*A***A*A*******A*A*A*A*
*A*AAAAAAA*A*A*AAA*AAA*AAAAA*AAAAA*A*A*AAAAAAA*AAAAA*AAAAAAAAAAAAAAAAA*AAA*AAAAA*A*AAA*AAA*AAAAA*A*A*
*A********AA*A*AAA*A**AA*******A**AA*AAA**A**A***AAA*A*******AAA*A*****AAA*A*A*A*A*****A*A**AA*A*A*A*
*AAAAAAAAA*AAA*A*AAA*A*AAA*AAA*AAAAA*A*A*AAAAA*AAA*A*A*AAAAAAA*AAA*AAA*A*A*A*AAA*AAA*AAA*AAAAA*A*AAA*
****A****A*A***A*A***A***A*A*AA********A*A**A**A****AA*******A*AA**AAA***A*AAA***A*A*A*******AA**A*A*
*AAAAAAA*AAAAAAA*AAAAAAA*A*A*A*AAAAAAAAAAA*AAAAAAAAAAA*AAAAAAA*A*AAA*AAA*A*A*A*AAA*AAA*AAAAA*AAAAA*A*
*A*A***A*************AAA*AAA*A*AAAA**A**AA**AAA**A*****AA**A*A*A*A*****A*AAA*A*A*A****A****A*****A*A*
*AAAAA*AAAAAAAAAAAAAAAAAAAAA*A*A*AAA*AAA*AAA*AAA*AAAAAAAAAAA*A*AAAAA*A*A*AAA*AAA*A*AAAAAAA*AAAAAAAAA*
*A**A**A*A*********A***A***A*A*A*AAAAA*****A*A*A*AA*****A**A*A*A**AA*A*A*A***A***A*A*****A*AA**A**AA*
*A*AAA*A*A*AAAAA*AAA*AAAAA*AAA*AAA*A*AAAAAAA*A*AAA*AAAAAAA*A*A*AAA*A*A*AAA*AAA*AAA*A*AAA*A*A*AAAAAAA*
*A*A*A*A*A*A*A*A*AAAAA*****A*******A*A*A*A*A*A*******A*A*A*AAAAA*A*A*A*A***A***AAA*A***AAA***A*A*A***
*A*AAA*AAAAAAA*A*A*A*AAA*AAA*AAAAAAA*A*AAA*A*A*AAAAA*A*AAA*AAA*A*AAAAA*A*AAA*A*AAA*AAAAA*AAA*AAAAAAA*
***A*A*******A*AAA*A***A*A***A*******AA****A*AAA***A*A*A*A*A*A*A*******A*A*A*A*A*A**A*AA***A*A*******
*AAA*AAAAAAA*A*A*A*A*AAA*A*AAA*A*AAAAA*AAAAA*A*A*A*A*A*A*A*A*A*AAAAA*AAAAA*AAAAA*AAAAA*A*A*AAAAAAAAA*
*A****A****A*A*A*AA*AA**AA*A*A*A*AAA*A*A***A*A*AAA*A***A***A*AA**A*A*A**AA*A*******A*A*A*A****A****A*
*AAAAAAAAA*AAAAA*AAAAAAA*AAAAA*AAA*AAA*AAA*AAAAA*AAAAAAA*AAAAAAA*A*A*AAA*A*AAAAA*AAA*AAA*AAAAA*AAA*A*
*A**A****A*A****************AA*AA**A*AA**A**A**A***A***A*A****AA*A*****A*A***A*A*A*AAAA**AAA***A*A*A*
*AAAAA*A*A*AAA*AAAAAAAAAAAAA*AAA*A*AAAAAAAAA*AAAAAAA*AAAAAAA*A*A*A*AAAAA*AAA*AAA*A*AAAAAAA*A*AAA*A*A*
***A*A*A*A*A*A*AA******AAA*A*AA**A***********A**A**A*******A*A*A*A*A*A****AA*****A*AA*****AA*A***A*A*
*AAA*AAA*A*A*AAAAAAAAA*AAA*A*AAA*AAAAAAA*AAAAA*AAA*AAAAAAAAA*A*A*A*A*A*AAA*AAAAAAA*A*AAAAAAA*AAA*A*A*
*A*****AAAAA**A******AA*AA*****A*A***A*A*A*****A*A**AA*A*****A*A*A*A***A*A**AA*A**AA*A*****A***A*A*A*
*AAAAAAA*AAAAAAAAAAAAAAAAAAAAAAAAAAAAA*AAA*AAAAA*AAAAAAA*AAAAAAAAA*AAAAA*AAAAAAA*AAAAA*AAAAAAAAAAAAA*
*****************************************************************************************************
]]

local variationsLayer_01 = [[
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRWWWWWWWWWWWWWWYYYYYYYUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYUUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYUUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYUUUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYYUUUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYYLUUUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYYLLLUUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYLLLLLUUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYLLLLLLLUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYYLLLLLLLLUUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLUUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLLLUUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLLZZZZZUUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLLLZZZZZZZZZZUUUUUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLLZZZZZZZZZZZZZZZZUUUUUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZUUUPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPPPPPPPPPPPPSSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYLLLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPPPPPPPPPPSSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYYLLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPPPPPPPPPSSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYLLLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPPPPPPPSSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYLLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPPPPPSSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYYLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPPPPSSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYLLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPPSSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPPPSSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYYLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPPPSSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYLLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPPSSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZPSSS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYYLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZS
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYLLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYYYLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYYLLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYYLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYYLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYLLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYYLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYLLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYYLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYLLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYYLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYLLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
RRRRRRRRRRRRRRYYYYYYYYYYLLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
]]

local entityLayer = entityLayer_01
local variationsLayer = variationsLayer_01

local mapName = 'random_mazes_001_intra_101x101_001'
local numMaps = 1
local chosenMap = random.uniformInt(0, numMaps-1)
local nextMapName = mapName--string.format('random_map_%03d', chosenMap)

local create_new_map = true
if create_new_map then
    local make_map = require 'common.make_map'
    make_map.makeMap(mapName
                     , entityLayer
                     , variationsLayer)
end

return factory.createLevelApi{
    mapName = mapName
    , blankMapName = 'random_mazes_001_intra_101x101_001_blank_name'
    , entityLayer = entityLayer
    , episodeLengthSeconds = 0.1 
    , scatteredRewardDensity = 0.25
    , minSpawnGoalDistance = 0
    , numMaps = numMaps
    , mapdir = 'random_mazes_001_intra_101x101'
}